### ISSUE TITLE
Problemas con los workflows

### ISSUE THREAD

**Issue by alu0101018300** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101018300#1]
Buenas, he configurado los workflows como en los tutoriales y como en el resto de las prácticas, pero en este caso no me funcionan, a pesar de que los tres me aparecen en la lista de actions, aunque no me hacen nada. No se por qué sucede esto, espero que me pueda ayudar. Muchas gracias y un saludo

**Comment by esegredo** [comment]
Hola Adrian,

Tus flujos de trabajo no funcionan porque están configurados para dispararse cada vez que haces un push o pull-request en la rama 'main'. Tu rama principal se llama 'master'.

O modificas el nombre de tu rama principal, o modificas los flujos de trabajo para que, en lugar de dispararse en 'main', se disparen en 'master'.

Saludos.

**Comment by alu0101018300** [comment]
Perfecto, ya funciona, muchas gracias y perdona las molestias
