### ISSUE TITLE
Problemas con los issues

### ISSUE THREAD

**Issue by alu0101018300** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101018300#3]
Buenas, cuando realizo las pruebas en mi terminal, en mi rama master me pasa todas las pruebas, pero en los workflows, no me pasan las pruebas y no entiendo por qué. Gracias y un saludo.

**Comment by esegredo** [comment]
Te había respondido a esto ya, ¿correcto?

**Comment by alu0101018300** [comment]
No, pero ya entiendo por qué, porque el directorio donde almaceno las notas tiene ruta local y por eso cuando la maquina virtual intenta ejecutar las pruebas no las pasa. Así que bueno, al menos entendí por qué era
